# Generated by Django 6.0.2 on 2026-02-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='file_hash',
        ),
    ]
