import React, { useEffect, useState } from 'react';
import { Descriptions, Collapse, Tag, Button, Spin, message, Progress, Dropdown } from 'antd';
import { DownloadOutlined, ShareAltOutlined, LoadingOutlined, ArrowRightOutlined, MailOutlined, WhatsAppOutlined, LinkOutlined, GoogleOutlined, ThunderboltOutlined } from '@ant-design/icons';
import GlassCard from '../components/GlassCard';
import ChatBot from '../components/ChatBot';
import Navbar from '../components/Navbar';
import { useParams } from 'react-router-dom';

const { Panel } = Collapse;

const Report = () => {
    const { id } = useParams();
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchReport = async () => {
            try {
                const response = await fetch(`http://127.0.0.1:8000/api/report/${id}/`);
                if (!response.ok) throw new Error('Failed to fetch report');
                const result = await response.json();
                setData(result);
            } catch (error) {
                console.error(error);
                message.error('Could not load report data');
            } finally {
                setLoading(false);
            }
        };

        if (id) fetchReport();
    }, [id]);

    if (loading) {
        return (
            <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] flex items-center justify-center">
                <Spin indicator={<LoadingOutlined style={{ fontSize: 48, color: '#6366f1' }} spin />} />
            </div>
        );
    }

    if (!data) {
        return <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] flex items-center justify-center">Report not found</div>;
    }

    // Safely parse potentially missing data
    const recs = data.suggested_changes || [];
    const gaps = data.critical_gaps || [];
    const score = data.relevance_score || 0;
    const summary = data.raw_output?.summary || "Analysis completed successfully. Review the detailed recommendations below.";

    // Determine status color
    const scoreColor = score >= 80 ? 'text-green-400' : score >= 60 ? 'text-orange-400' : 'text-red-400';
    const alignment = score >= 80 ? 'High' : score >= 60 ? 'Moderate' : 'Low';
    const scoreLabel = score >= 80 ? 'Excellent' : score >= 60 ? 'Good' : score >= 40 ? 'Needs Improvement' : 'Critical';

    const shareUrl = window.location.href;
    const shareText = `Check out this curriculum analysis for ${data.program_name}!`;

    const shareMenu = {
        items: [
            {
                key: '1',
                label: 'Copy Link',
                icon: <LinkOutlined />,
                onClick: () => {
                    navigator.clipboard.writeText(shareUrl);
                    message.success('Link copied!');
                }
            },
            {
                key: '2',
                label: 'Gmail',
                icon: <MailOutlined />,
                onClick: () => window.open(`https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent("Curriculum Analysis Report")}&body=${encodeURIComponent(shareText + "\n\n" + shareUrl)}`, '_blank')
            },
            {
                key: '3',
                label: 'WhatsApp',
                icon: <WhatsAppOutlined />,
                onClick: () => window.open(`https://wa.me/?text=${encodeURIComponent(shareText + " " + shareUrl)}`, '_blank')
            },
            {
                key: '4',
                label: 'Google Drive',
                icon: <GoogleOutlined />,
                onClick: () => window.open(`https://drive.google.com/`, '_blank')
            }
        ]
    };

    const handleExport = () => {
        window.print();
    };

    return (
        <>
            {/* ===== WEB VIEW (hidden during print) ===== */}
            <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] print:hidden">
                <Navbar />
                <div className="pt-24 px-8 max-w-6xl mx-auto pb-10">
                    <header className="flex justify-between items-start mb-8">
                        <div>
                            <div className="flex items-center gap-3 mb-2">
                                <h1 className="text-3xl font-bold">Analysis Report</h1>
                                <Tag color="blue" className="text-sm px-3 py-0.5 rounded-full border-none bg-blue-500/20 text-blue-400">Generated by AI</Tag>
                            </div>
                            <p className="text-[var(--text-muted)]">{data.program_name} • {new Date(data.created_at).toLocaleDateString()}</p>
                        </div>
                        <div className="flex gap-3">
                            <Dropdown menu={shareMenu} placement="bottomRight" arrow>
                                <Button icon={<ShareAltOutlined />} className="bg-transparent border-2 border-[var(--text-muted)] text-[var(--text-primary)] hover:border-indigo-400 hover:text-indigo-400 transition-all">Share</Button>
                            </Dropdown>
                            <Button type="primary" icon={<DownloadOutlined />} className="bg-indigo-600" onClick={handleExport}>Export PDF</Button>
                        </div>
                    </header>

                    <div className="grid lg:grid-cols-3 gap-6">
                        <div className="lg:col-span-2 space-y-6">
                            <GlassCard>
                                <Descriptions title={<span className="text-[var(--text-primary)] text-lg">Executive Summary</span>} layout="vertical" column={3} bordered className="glass-descriptions">
                                    <Descriptions.Item label={<span className="text-[var(--text-muted)]">Relevance Score</span>}>
                                        <div className="flex items-center gap-4">
                                            <Progress
                                                type="dashboard"
                                                percent={score}
                                                strokeColor={score >= 80 ? '#4ade80' : score >= 60 ? '#fb923c' : '#f87171'}
                                                trailColor="rgba(255,255,255,0.1)"
                                                format={(percent) => <span className={`text-2xl font-bold ${scoreColor}`}>{percent}</span>}
                                                width={120}
                                                strokeWidth={10}
                                                gapDegree={60}
                                            />
                                        </div>
                                    </Descriptions.Item>
                                    <Descriptions.Item label={<span className="text-[var(--text-muted)]">Topics Analyzed</span>}>
                                        <span className="text-xl font-bold text-[var(--text-primary)]">{data.topics_extracted}</span>
                                    </Descriptions.Item>
                                    <Descriptions.Item label={<span className="text-[var(--text-muted)]">Market Alignment</span>}>
                                        <span className="text-xl font-bold text-[var(--text-primary)]">{alignment}</span>
                                    </Descriptions.Item>
                                </Descriptions>

                                <div className="mt-6">
                                    <h3 className="font-bold mb-2 text-[var(--text-primary)]">Key Insights</h3>
                                    <p className="text-[var(--text-muted)] text-sm leading-relaxed">
                                        {summary}
                                    </p>
                                </div>
                            </GlassCard>

                            <GlassCard>
                                <h3 className="text-xl font-bold mb-4 text-[var(--text-primary)]">Detailed Recommendations</h3>
                                {recs.length > 0 ? (
                                    <Collapse accordion ghost className="site-collapse-custom-collapse">
                                        {recs.map((item, idx) => (
                                            <Panel
                                                header={<span className="text-[var(--text-primary)] font-semibold">{item.what_to_update}</span>}
                                                key={idx}
                                                extra={<Tag color="green">Suggestion</Tag>}
                                            >
                                                <p className="text-[var(--text-muted)]">{item.why_to_update}</p>
                                                {item.resource_texts && (
                                                    <div className="mt-2 text-xs">
                                                        <span className="text-[var(--text-faint)] mr-2">Resources:</span>
                                                        <a
                                                            href={`https://www.google.com/search?q=${encodeURIComponent(item.resource_texts + " tutorial course")}`}
                                                            target="_blank"
                                                            rel="noopener noreferrer"
                                                            className="text-indigo-400 hover:text-indigo-300 underline"
                                                        >
                                                            {item.resource_texts} <ArrowRightOutlined className="text-[10px]" />
                                                        </a>
                                                    </div>
                                                )}
                                            </Panel>
                                        ))}
                                    </Collapse>
                                ) : (
                                    <p className="text-[var(--text-faint)]">No specific recommendations generated.</p>
                                )}
                            </GlassCard>

                            {gaps.length > 0 && (
                                <GlassCard>
                                    <h3 className="text-xl font-bold mb-4 text-red-400">Critical Gaps Identified</h3>
                                    <ul className="list-disc pl-5 space-y-2 text-[var(--text-secondary)]">
                                        {gaps.map((gap, i) => (
                                            <li key={i}>{gap}</li>
                                        ))}
                                    </ul>
                                </GlassCard>
                            )}
                        </div>

                        <div className="space-y-6">
                            <GlassCard>
                                <h3 className="text-lg font-bold mb-4">Job Market Match</h3>
                                <div className="space-y-4">
                                    <div>
                                        <div className="flex justify-between text-sm mb-1">
                                            <span className="text-[var(--text-muted)]">Calculated Alignment</span>
                                            <span className={scoreColor}>{score}%</span>
                                        </div>
                                        <div className="w-full bg-[var(--bg-secondary)] rounded-full h-2">
                                            <div
                                                className={`h-2 rounded-full ${score >= 80 ? 'bg-green-500' : 'bg-orange-500'}`}
                                                style={{ width: `${score}%` }}
                                            ></div>
                                        </div>
                                    </div>
                                </div>
                            </GlassCard>

                            <GlassCard>
                                <h3 className="text-lg font-bold mb-4">Files Analyzed</h3>
                                <ul className="text-sm text-[var(--text-muted)] space-y-2">
                                    {(data.syllabus_file_names || []).map((file, i) => (
                                        <li key={i} className="truncate">• {file}</li>
                                    ))}
                                </ul>
                            </GlassCard>
                        </div>
                    </div>
                </div>
                {/* Floating Chat Bot */}
                <ChatBot analysisId={id} />
            </div>

            {/* ===== PRINT VIEW (hidden on screen, shown only during print) ===== */}
            <div className="hidden print:block print-report">
                {/* Cover / Header */}
                <div className="print-header">
                    <div className="print-logo">
                        <span className="print-logo-icon">⚡</span>
                        <span>CodeVengers</span>
                    </div>
                    <h1 className="print-title">Curriculum Analysis Report</h1>
                    <div className="print-meta">
                        <span><strong>Program:</strong> {data.program_name}</span>
                        <span><strong>Date:</strong> {new Date(data.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
                        <span><strong>Report ID:</strong> #{id}</span>
                    </div>
                </div>

                <hr className="print-divider" />

                {/* Executive Summary */}
                <section className="print-section">
                    <h2 className="print-section-title">1. Executive Summary</h2>
                    <div className="print-stats-grid">
                        <div className="print-stat-box">
                            <div className="print-stat-label">Relevance Score</div>
                            <div className="print-stat-value">{score}<span className="print-stat-unit">/100</span></div>
                            <div className="print-stat-badge" data-level={scoreLabel.toLowerCase().replace(' ', '-')}>{scoreLabel}</div>
                        </div>
                        <div className="print-stat-box">
                            <div className="print-stat-label">Topics Analyzed</div>
                            <div className="print-stat-value">{data.topics_extracted}</div>
                        </div>
                        <div className="print-stat-box">
                            <div className="print-stat-label">Market Alignment</div>
                            <div className="print-stat-value print-stat-value-text">{alignment}</div>
                        </div>
                        <div className="print-stat-box">
                            <div className="print-stat-label">Files Analyzed</div>
                            <div className="print-stat-value">{(data.syllabus_file_names || []).length}</div>
                        </div>
                    </div>

                    <div className="print-insight-box">
                        <h3 className="print-insight-title">Key Insights</h3>
                        <p className="print-insight-text">{summary}</p>
                    </div>
                </section>

                {/* Score Breakdown */}
                {data.raw_output?.score_breakdown && (
                    <section className="print-section">
                        <h2 className="print-section-title">2. Score Methodology</h2>
                        <div className="print-score-breakdown">
                            <div className="print-score-row">
                                <span>LLM Analysis Score</span>
                                <span><strong>{data.raw_output.score_breakdown.llm_score}</strong>/100 (weight: {data.raw_output.score_breakdown.weights.llm * 100}%)</span>
                            </div>
                            <div className="print-score-row">
                                <span>Embedding Similarity Score</span>
                                <span><strong>{data.raw_output.score_breakdown.embedding_score}</strong>/100 (weight: {data.raw_output.score_breakdown.weights.embedding * 100}%)</span>
                            </div>
                            <div className="print-score-row print-score-total">
                                <span>Final Hybrid Score</span>
                                <span><strong>{score}</strong>/100</span>
                            </div>
                        </div>
                    </section>
                )}

                {/* Critical Gaps */}
                {gaps.length > 0 && (
                    <section className="print-section">
                        <h2 className="print-section-title">{data.raw_output?.score_breakdown ? '3' : '2'}. Critical Gaps Identified</h2>
                        <table className="print-table">
                            <thead>
                                <tr>
                                    <th style={{ width: '40px' }}>#</th>
                                    <th>Missing Skill / Topic</th>
                                </tr>
                            </thead>
                            <tbody>
                                {gaps.map((gap, i) => (
                                    <tr key={i}>
                                        <td className="print-table-num">{i + 1}</td>
                                        <td>{gap}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </section>
                )}

                {/* Recommendations */}
                {recs.length > 0 && (
                    <section className="print-section">
                        <h2 className="print-section-title">{data.raw_output?.score_breakdown ? (gaps.length > 0 ? '4' : '3') : (gaps.length > 0 ? '3' : '2')}. Detailed Recommendations</h2>
                        <table className="print-table">
                            <thead>
                                <tr>
                                    <th style={{ width: '40px' }}>#</th>
                                    <th style={{ width: '30%' }}>What to Update</th>
                                    <th style={{ width: '45%' }}>Why</th>
                                    <th style={{ width: '25%' }}>Suggested Resources</th>
                                </tr>
                            </thead>
                            <tbody>
                                {recs.map((item, idx) => (
                                    <tr key={idx} className="break-inside-avoid">
                                        <td className="print-table-num">{idx + 1}</td>
                                        <td><strong>{item.what_to_update}</strong></td>
                                        <td>{item.why_to_update}</td>
                                        <td className="print-resource">{item.resource_texts || '—'}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </section>
                )}

                {/* Files Analyzed */}
                <section className="print-section">
                    <h2 className="print-section-title">Files Analyzed</h2>
                    <ul className="print-file-list">
                        {(data.syllabus_file_names || []).map((file, i) => (
                            <li key={i}>{file}</li>
                        ))}
                    </ul>
                </section>

                {/* Footer */}
                <div className="print-footer">
                    <hr className="print-divider" />
                    <div className="print-footer-content">
                        <span>Generated by <strong>CodeVengers Curriculum AI</strong></span>
                        <span>Report #{id} • {new Date(data.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
                    </div>
                    <p className="print-disclaimer">This report was generated using AI-powered analysis. Results should be reviewed by domain experts before implementation.</p>
                </div>
            </div>
        </>
    );
};

export default Report;
